var DEFAULT_MARGIN = 16

var MAP_AREA_HEIGHT = 164

var HEADER_DEFAULT_HEIGHT_PORTRAIT          = 72
var HEADER_DEFAULT_HEIGHT_LANDSCAPE         = 52
var HEADER_DEFAULT_TOP_SPACING_PORTRAIT     = 20
var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE    = 16

var FONT_FAMILY = 'Nokia Pure Text'
var FONT_FAMILY_LIGHT = 'Nokia Pure Light'

var FONT_XXXLARGE   = 40
var FONT_XLARGE     = 32
var FONT_LARGE      = 28
var FONT_SLARGE     = 26
var FONT_DEFAULT    = 24
var FONT_LSMALL     = 22
var FONT_SMALL      = 20
var FONT_XSMALL     = 18
var FONT_XXSMALL    = 16

var HEADER_BACKGROUND_COLOR = 'darkgreen'
var HEADER_FOREGROUND_COLOR = 'white'

var MAP_POSITION_INNER_CIRCLE_COLOR = '#80006400'
var MAP_POSITION_OUTER_CIRCLE_COLOR = 'darkgreen'
var MAP_POLYLINE_COLOR = 'darkgreen'

var MAP_RECTANGLE_BACKGROUND_COLOR = '#80808080'
var MAP_RECTANGLE_BORDER_COLOR = 'darkgrey'

var REMOTE_FETCH_ACTION = 0
var LOCAL_FETCH_ACTION  = 1
var LOCAL_SAVE_ACTION   = 2
var SINGLE_SHOT_ACTION  = 3

var REMOTE_FETCH_RESPONSE   = 0
var LOCAL_FETCH_RESPONSE    = 1
var LOCAL_SAVE_RESPONSE     = 2
var SINGLE_SHOT_RESPONSE    = 3

var COLOR_FOREGROUND            = '#191919'
var COLOR_INVERTED_FOREGROUND   = '#FFFFFF'
var COLOR_BUTTON_DISABLED_FOREGROUND    = '#B2B2B4'

// ListDelegate
var LIST_ITEM_MARGIN    = 16
var LIST_ITEM_SPACING   = 16
var LIST_ICON_SIZE      = 64
var LIST_ITEM_HEIGHT        = 80
var LIST_ITEM_HEIGHT_SMALL  = 64

var MARGIN_XLARGE = 16

var LIST_TILE_SIZE      = 26
var LIST_TITLE_COLOR                    = '#282828'
var LIST_TITLE_COLOR_PRESSED            = '#797979'
var LIST_TITLE_COLOR_INVERTED           = '#ffffff'
var LIST_TITLE_COLOR_PRESSED_INVERTED   = '#797979'

var LIST_SUBTILE_SIZE = 22
var LIST_SUBTITLE_COLOR                     = '#505050'
var LIST_SUBTITLE_COLOR_PRESSED             = '#797979'
var LIST_SUBTITLE_COLOR_INVERTED            = '#C8C8C8'
var LIST_SUBTITLE_COLOR_PRESSED_INVERTED    = '#797979'
