var DEFAULT_MARGIN = 16

var MAP_AREA_HEIGHT = 164

var HEADER_DEFAULT_HEIGHT_PORTRAIT          = 72
var HEADER_DEFAULT_HEIGHT_LANDSCAPE         = 52
var HEADER_DEFAULT_TOP_SPACING_PORTRAIT     = 20
var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE    = 16

var FONT_FAMILY = 'Nokia Pure Text'
var FONT_FAMILY_LIGHT = 'Nokia Pure Light'

var FONT_XXXLARGE   = 40
var FONT_XLARGE     = 32
var FONT_LARGE      = 28
var FONT_SLARGE     = 26
var FONT_DEFAULT    = 24
var FONT_LSMALL     = 22
var FONT_SMALL      = 20
var FONT_XSMALL     = 18
var FONT_XXSMALL    = 16

var HEADER_BACKGROUND_COLOR = '#d4060d'
var HEADER_FOREGROUND_COLOR = 'white'
